# Generated by Django 5.0 on 2023-12-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=127)),
                ('R_count', models.IntegerField(default=0)),
                ('I_count', models.IntegerField(default=0)),
                ('A_count', models.IntegerField(default=0)),
                ('S_count', models.IntegerField(default=0)),
                ('E_count', models.IntegerField(default=0)),
                ('C_count', models.IntegerField(default=0)),
            ],
        ),
    ]
